node {
     def nodeHome = tool name: 'node-11.0.0', type: 'jenkins.plugins.nodejs.tools.NodeJSInstallation'
   
    stage('check tools') {
        sh "node -v"
        sh "npm -v"
    }
    stage('NPM Install') {
	    sh 'npm install -g @angular/cli'
	    sh 'npm install'
    }
}
