pipeline{
agent any
  tools {nodejs "nodejs"}
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('install modules'){
      steps{
        sh '''
           npm install -g @angular/cli;
	      npm install;
        '''
      }
    }
    stage ('build') {
      steps{
        sh 'ng build --prod'
      }
    }
  }
  }
