pipeline{
agent any
  tools {nodejs "nodejs"}
  stages{
    stage ('checkout'){
      steps{
        checkout scm
      }
    }
    stage ('install modules'){
      steps{
        sh '''
           npm install -g @angular/cli;
        '''
      }
    }
    stage ('copy') {
      steps{	      
	      sh 'cp -r Angular-HelloWorld-master /tmp'
      }
    }
    stage ('build') {
      steps{
      
	      dir("/tmp/Angular-HelloWorld-master") {
		      sh 'npm install'
		      sh 'ng build --prod'
	      }
      }
    }
  }
  }
